name: Deploy to App Runner - Test Environment

on:
  workflow_run:
    workflows:
      - "Deploy to App Runner - Dev Environment"
    types:
      - completed

jobs:
  deploy_test:
    runs-on: ubuntu-latest
    steps:
      # Steps for deploying to the test environment
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to App Runner - Test Environment
        id: deploy-apprunner-test
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: techno-app-runner-test
          image: ${{ github.event.workflow_run.outputs['Deploy to App Runner - Dev Environment'].steps.deploy-apprunner-dev.outputs.image }}
          access-role-arn: ${{ secrets.ROLE_ARN }}
          region: us-east-1  # Update with the desired region for the test environment
          wait-for-service-stability: true
