name: Deploy to App Runner - Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'In which environment would you like to deploy this application: Test'
        required: true
        options:
          - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to App Runner - Test Environment
        id: deploy-apprunner-test
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: techno-app-runner
          image: ${{ needs.deploy-dev.outputs.image }}
          access-role-arn: ${{ secrets.ROLE_ARN }}
          region: us-east-1
          wait-for-service-stability-seconds: 300

      - name: App Runner Test Environment Output
        run: echo "App runner test environment output ${{ steps.deploy-apprunner-test.outputs.service-id }}"
