name: Deploy to Dev Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to Dev Environment'
        required: true
        options:
          - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact from Main Workflow
        uses: actions/download-artifact@v2
        with:
          name: image-artifact
          path: ./artifacts

      - name: Deploy to App Runner - Dev Environment
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: techno-app-runner
          image: ${{ env.IMAGE_FROM_MAIN }}
          access-role-arn: ${{ secrets.ROLE_ARN }}
          region: us-west-2 # Update with the desired region for the dev environment
          wait-for-service-stability: true
