name: Deploy to App Runner - Dev

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'In which environment would you like to deploy this application: Dev, Test, or Prod?'
        required: true
        options:
          - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push image to Amazon ECR
        id: build-image
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/nodejs:${{ github.sha }} .
          docker push ${{ secrets.ECR_REGISTRY }}/nodejs:${{ github.sha }}

      - name: Deploy to App Runner - Dev Environment
        id: deploy-apprunner-dev
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: techno-app-runner
          image: ${{ secrets.ECR_REGISTRY }}/nodejs:${{ github.sha }}
          access-role-arn: ${{ secrets.ROLE_ARN }}
          region: us-west-2  # Update with the desired region for the dev environment
          wait-for-service-stability: true

      - name: App Runner Dev Environment Output
        run: echo "App runner dev environment output ${{ steps.deploy-apprunner-dev.outputs.service-id }}"
