name: Deploy to App Runner - Test Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'In which environment would you like to deploy this application: Dev, Test, or Prod?'
        required: true
        options:
          - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Deploy to App Runner - Test Environment
        id: deploy-apprunner-test
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: techno-app-runner
          image: ${{ github.event.repository.owner.login }}/nodejs:${{ github.sha }}
          access-role-arn: ${{ secrets.ROLE_ARN }}
          region: us-east-1 # Update with the desired region for the test environment
          wait-for-service-stability-seconds: 300 # Update with the desired timeout duration
