name: Deploy to App Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run start

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          aws ecr create-repository --repository-name sushant-technocirrus || true
          docker build -t sushant-technocirrus .
          docker tag sushant-technocirrus:latest 285984116532.dkr.ecr.us-west-2.amazonaws.com/sushant-technocirrus:latest
          docker push 285984116532.dkr.ecr.us-west-2.amazonaws.com/sushant-technocirrus:latest

      - name: Deploy to App Runner
        uses: aws-actions/aws-apprunner-action@v1
        with:
          name: sushant-technocirrus
          image: 285984116532.dkr.ecr.us-west-2.amazonaws.com/sushant-technocirrus:latest
          port: 3000
