name: Deploy to App Runner - Image based

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: nodejs
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Deploy to App Runner - Dev Environment
        if: github.ref == 'refs/heads/main'
        id: deploy-apprunner-dev
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: techno-app-runner
          image: ${{ steps.build-image.outputs.image }}
          access-role-arn: ${{ secrets.ROLE_ARN }}
          region: us-west-2 # Update with the desired region for the dev environment
          wait-for-service-stability: true
          
      - name: Manual Approval for Test Environment
        if: github.ref == 'refs/heads/main' && steps.deploy-apprunner-dev.outcome == 'success'
        id: approval-test
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('::warning::Please manually approve the deployment to the Test environment.');
            console.log('::set-output name=approval-status::approved');
          
      - name: Deploy to App Runner - Test Environment
        if: steps.approval-test.outputs.approval-status == 'approved'
        id: deploy-apprunner-test
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: techno-app-runner
          image: ${{ steps.build-image.outputs.image }}
          access-role-arn: ${{ secrets.ROLE_ARN }}
          region: us-east-1 # Update with the desired region for the test environment
          wait-for-service-stability: true
          
      - name: Manual Approval for Prod Environment
        if: github.ref == 'refs/heads/main' && steps.deploy-apprunner-test.outcome == 'success'
        id: approval-prod
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('::warning::Please manually approve the deployment to the Prod environment.');
            console.log('::set-output name=approval-status::approved');
          
      - name: Deploy to App Runner - Prod Environment
        if: steps.approval-prod.outputs.approval-status == 'approved'
        id: deploy-apprunner-prod
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: techno-app-runner
          image: ${{ steps.build-image.outputs.image }}
          access-role-arn: ${{ secrets.ROLE_ARN }}
          region: us-east-2 # Update with the desired region for the prod environment
          wait-for-service-stability: true

      - name: App Runner Dev Environment Output
        if: github.ref == 'refs/heads/main'
        run: echo "App runner dev environment output ${{ steps.deploy-apprunner-dev.outputs.service-id }}"

      - name: App Runner Test Environment Output
        if: steps.approval-test.outputs.approval-status == 'approved'
        run: echo "App runner test environment output ${{ steps.deploy-apprunner-test.outputs.service-id }}"

      - name: App Runner Prod Environment Output
        if: steps.approval-prod.outputs.approval-status == 'approved'
        run: echo "App runner prod environment output ${{ steps.deploy-apprunner-prod.outputs.service-id }}"
