name: Deploy to AWS App Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Configure AWS ECR registry
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 285984116532.dkr.ecr.us-west-2.amazonaws.com
      
      - name: Build and push Docker image
        run: |
          docker build -t 285984116532.dkr.ecr.us-west-2.amazonaws.com:latest .
          docker push 285984116532.dkr.ecr.us-west-2.amazonaws.com:latest

      - name: Deploy to App Runner
        run: |
          aws apprunner create-service --service-name app-runner-service \
            --source-configuration "RepositoryType=ECR,ImageRepository=285984116532.dkr.ecr.us-west-2.amazonaws.com,ImageIdentifier=latest" \
            --region your-us-west-2
