name: Deploy to App Runner - Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'In which environment would you like to deploy this application: Dev, Test, or Prod?'
        required: true
        options:
          - dev
          - test
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test

    needs: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Deploy to App Runner - Test Environment
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'test'
        id: deploy-apprunner-test
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: techno-app-runner
          image: ${{ needs.dev.outputs.deploy-apprunner-dev.outputs.service-id }}
          access-role-arn: ${{ secrets.ROLE_ARN }}
          region: us-east-1  # Update with the desired region for the test environment
          wait-for-service-stability: true

      - name: App Runner Test Environment Output
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'test'
        run: echo "App runner test environment output ${{ steps.deploy-apprunner-test.outputs.service-id }}"
